USE TN_CSDLPT
GO
--LẤY THÔNG TIN TOÀN BỘ TỪ (CƠ SỞ)
CREATE PROC [dbo].[SP_LayThongTinCacKhoa]
AS
	SELECT * FROM KHOA
GO
CREATE PROC [dbo].[SP_LayThongTinCacGiaoVien]
AS
	SELECT * FROM GIAOVIEN
GO
CREATE PROC [dbo].[SP_LayThongTinCacLop]
AS
	SELECT * FROM LOP
GO
CREATE PROC [dbo].[SP_LayThongTinCacMonHoc]
AS
	SELECT * FROM MONHOC
GO
CREATE PROC [dbo].[SP_LayThongTinCacSinhVien]
AS
	SELECT * FROM SINHVIEN
GO
--LẤY CÂU HỎI CỦA GIÁO VIÊN
CREATE PROC [dbo].[SP_LayCauHoi]
@MAGV NCHAR(8)
AS
	SELECT * FROM BODE WHERE MAGV=@MAGV
GO
--LẤY CÂU HỎI TRÌNH ĐỘ
CREATE PROC [dbo].[SP_LayCauHoiTrinhDo]
@TRINHDO nchar(1)
AS
	SELECT * FROM BODE WHERE TRINHDO=@TRINHDO
GO
--LẤY CÂU HỎI CÓ TRÌNH ĐỘ & SỐ CÂU
CREATE PROC [dbo].[SP_LayNCauHoiTrinhDo]
@TRINHDO nchar(1),
@N INT
AS
	SELECT TOP (@N) * FROM BODE WHERE TRINHDO=@TRINHDO
GO
