--THÊM GIÁO VIÊN
ALTER PROC [dbo].[SP_ThemGiaoVien]
@MAGV nchar(8),
@HO NVARCHAR(50),
@TEN NVARCHAR(10),
@HOCVI NVARCHAR(40),
@MAKH nchar(8)
AS
if exists(select MAGV FROM GIAOVIEN WHERE MAGV=@MAGV) RAISERROR('DA TON TAI MA GIAO VIEN NAY',16,1,50002)
ELSE
	insert into GIAOVIEN (MAGV, HO, TEN, HOCVI, MAKH) 
	VALUES (@MAGV, @HO, @TEN, @HOCVI, @MAKH)
--THÊM SINH VIÊN
ALTER PROC [dbo].[SP_ThemSinhVien]
@MASV nchar(8),
@HO NVARCHAR(50),
@TEN NVARCHAR(10),
@NGAYSINH date,
@DIACHI NVARCHAR(100),
@MALOP nchar(15),
@PASSWORD NVARCHAR(30)
AS
if exists(select MASV FROM SINHVIEN WHERE MASV=@MASV) RAISERROR('DA TON TAI MA SINH VIEN NAY',16,1,50006)
ELSE
insert into SINHVIEN (MASV, HO, TEN, NGAYSINH, DIACHI, MALOP, PASSWORD) 
VALUES (@MASV, @HO, @TEN, @NGAYSINH, @DIACHI, @MALOP, @PASSWORD)
--THÊM MÔN HỌC
ALTER PROC [dbo].[SP_ThemMonHoc]
@MAMH nchar(5),
@TENMH NVARCHAR(50)
AS
if exists(select MAMH FROM MONHOC WHERE MAMH=@MAMH) RAISERROR('DA TON TAI MA MON HOC NAY',16,1,50005)
ELSE
insert into MONHOC(MAMH, TENMH) 
VALUES (@MAMH, @TENMH)
--THÊM LỚP
ALTER PROC [dbo].[SP_ThemLop]
@MALOP nchar(8),
@TENLOP NVARCHAR(50),
@MAKH nchar(3)
AS
if exists(select MALOP FROM LOP WHERE MALOP=@MALOP) RAISERROR('DA TON TAI MA LOP NAY',16,1,50004)
ELSE
insert into LOP (MALOP, TENLOP, MAKH) 
VALUES (@MALOP, @TENLOP, @MAKH)
--THÊM KHOA
ALTER PROC [dbo].[SP_ThemKhoa]
@MAKH nchar(8),
@TENKH NVARCHAR(50),
@MACS nchar(3)
AS
if exists(select MAKH FROM KHOA WHERE MAKH=@MAKH) RAISERROR('DA TON TAI MA KHOA NAY',16,1,50003)
ELSE
insert into KHOA (MAKH, TENKH, MACS) 
VALUES (@MAKH, @TENKH, @MACS)