USE TN_CSDLPT
GO
--XÓA KHOA
CREATE PROC [dbo].[SP_XoaKhoa]
@MAKH NCHAR(8)
AS
	DECLARE @LOG INT
	SET @LOG=0
	IF EXISTS(SELECT MAGV FROM GIAOVIEN WHERE MAKH=@MAKH) SET @LOG=50007
	ELSE IF EXISTS(SELECT MALOP FROM LOP WHERE MAKH=@MAKH) SET @LOG=50008
	ELSE DELETE FROM KHOA WHERE MAKH=@MAKH
	IF (@LOG<>0)
	RAISERROR('THONG TIN KHOA DANG CHUA DU LIEU',16,1,@LOG)
GO
--XÓA LỚP
CREATE PROC [dbo].[SP_XoaLop]
@MALOP NCHAR(8)
AS
	DECLARE @LOG INT
	SET @LOG=0
	IF EXISTS(SELECT MASV FROM SINHVIEN WHERE MALOP=@MALOP) SET @LOG=50009
	ELSE IF EXISTS(SELECT MALOP FROM GV_DANGKY WHERE MALOP=@MALOP) SET @LOG=50010
	ELSE DELETE FROM LOP WHERE MALOP=@MALOP
	IF (@LOG<>0)
	RAISERROR('THONG TIN LOP DANG CHUA DU LIEU',16,1,@LOG)
GO