--LẤY THÔNG TIN TÀI KHOẢN TỪ LOGIN
CREATE PROC SP_Lay_Thong_Tin_Tu_Login @TENLOGIN NVARCHAR(100)
AS
	BEGIN
		DECLARE @UID INT
		DECLARE @UNAME VARCHAR(10)

		IF EXISTS(SELECT * FROM sys.sysusers WHERE sid = SUSER_SID(@TENLOGIN))
		BEGIN
			SELECT @UID=uid , @UNAME=NAME FROM sys.sysusers WHERE sid = SUSER_SID(@TENLOGIN)
			--NHÓM COSO & GIAOVIEN
			IF EXISTS(SELECT TEN FROM GIAOVIEN WHERE MAGV=@TENLOGIN)
				SELECT LOGINNAME= @UNAME, 
				   NGUOIDUNG = (SELECT HO+ ' '+TEN FROM GIAOVIEN WHERE MAGV=@UNAME), 
				   TENNHOM=NAME
				FROM sys.sysusers
				WHERE uid = (SELECT groupuid FROM sys.sysmembers WHERE memberuid=@UID)
			-- NHÓM TRUONG
			ELSE
				SELECT LOGINNAME= @UNAME, 
				   NGUOIDUNG = 'HOC VIEN',
				   TENNHOM=NAME
				FROM sys.sysusers
				WHERE UID = (SELECT groupuid FROM sys.sysmembers WHERE memberuid=@UID)
		END
		--NHÓM SINHVIEN
		ELSE IF EXISTS(SELECT MASV,PASSWORD FROM SINHVIEN WHERE MASV=@TENLOGIN)
		BEGIN
				SELECT LOGINNAME='SV', --TK LOGIN VÀO SERVER
					NGUOIDUNG = (SELECT HO+' '+TEN FROM SINHVIEN WHERE MASV=@TENLOGIN),
					TENNHOM=S.NAME --'SINHVIEN'
				-- vvv CÓ THỂ BỎ
				FROM sys.sysusers S
				WHERE S.UID = (SELECT groupuid FROM sys.sysmembers WHERE memberuid=(SELECT uid FROM sys.sysusers WHERE name='SV'))--USERNAME TRUY CẬP DB VỚI ROLE SINHVIEN
				-- ^^^	
		END
		ELSE RAISERROR('KHONG TIM THAY TEN DANG NHAP',16,1,50001)
	END