--CHỌN CƠ SỞ (TỪ SITE CHỦ)
CREATE VIEW Get_Subscribes
AS
	SELECT TENCS=PUBS.description, TENSERVER=subscriber_server
	 FROM sysmergepublications  PUBS, sysmergesubscriptions SUBS
	 WHERE PUBS.pubid = SUBS.pubid AND  publisher <> subscriber_server
GO
--LẤY THÔNG TIN TÀI KHOẢN TỪ LOGIN
CREATE PROC SP_Lay_Thong_Tin_Tu_Login @TENLOGIN NVARCHAR(100)
AS
	BEGIN
		DECLARE @UID INT
		DECLARE @UNAME VARCHAR(10)

		IF EXISTS(SELECT * FROM sys.sysusers WHERE sid = SUSER_SID(@TENLOGIN))
		BEGIN
			SELECT @UID=uid , @UNAME=NAME FROM sys.sysusers WHERE sid = SUSER_SID(@TENLOGIN)
			--NHÓM COSO & GIAOVIEN
			IF EXISTS(SELECT TEN FROM GIAOVIEN WHERE MAGV=@TENLOGIN)
				SELECT LOGINNAME= @UNAME, 
				   NGUOIDUNG = (SELECT HO+ ' '+TEN FROM GIAOVIEN WHERE MAGV=@UNAME), 
				   TENNHOM=NAME
				FROM sys.sysusers
				WHERE uid = (SELECT groupuid FROM sys.sysmembers WHERE memberuid=@UID)
			-- NHÓM TRUONG
			ELSE
				SELECT LOGINNAME= @UNAME, 
				   NGUOIDUNG = 'HOC VIEN',
				   TENNHOM=NAME
				FROM sys.sysusers
				WHERE UID = (SELECT groupuid FROM sys.sysmembers WHERE memberuid=@UID)
		END
		--NHÓM SINHVIEN
		ELSE IF EXISTS(SELECT MASV,PASSWORD FROM SINHVIEN WHERE MASV=@TENLOGIN)
		BEGIN
				SELECT LOGINNAME='SV', --TK LOGIN VÀO SERVER
					NGUOIDUNG = (SELECT HO+' '+TEN FROM SINHVIEN WHERE MASV=@TENLOGIN),
					TENNHOM=S.NAME --'SINHVIEN'
				-- vvv CÓ THỂ BỎ
				FROM sys.sysusers S
				WHERE S.UID = (SELECT groupuid FROM sys.sysmembers WHERE memberuid=(SELECT uid FROM sys.sysusers WHERE name='SV'))--USERNAME TRUY CẬP DB VỚI ROLE SINHVIEN
				-- ^^^	
		END
		ELSE RAISERROR('KHONG TIM THAY TEN DANG NHAP',16,1,50001)
	END
--THÊM GIÁO VIÊN
ALTER PROC [dbo].[SP_ThemGiaoVien]
@MAGV nchar(8),
@HO NVARCHAR(50),
@TEN NVARCHAR(10),
@HOCVI NVARCHAR(40),
@MAKH nchar(8)
AS
if exists(select MAGV FROM GIAOVIEN WHERE MAGV=@MAGV) RAISERROR('DA TON TAI MA GIAO VIEN NAY',16,1,50002)
ELSE
	insert into GIAOVIEN (MAGV, HO, TEN, HOCVI, MAKH) 
	VALUES (@MAGV, @HO, @TEN, @HOCVI, @MAKH)
--THÊM SINH VIÊN
ALTER PROC [dbo].[SP_ThemSinhVien]
@MASV nchar(8),
@HO NVARCHAR(50),
@TEN NVARCHAR(10),
@NGAYSINH date,
@DIACHI NVARCHAR(100),
@MALOP nchar(15),
@PASSWORD NVARCHAR(30)
AS
if exists(select MASV FROM SINHVIEN WHERE MASV=@MASV) RAISERROR('DA TON TAI MA SINH VIEN NAY',16,1,50006)
ELSE
insert into SINHVIEN (MASV, HO, TEN, NGAYSINH, DIACHI, MALOP, PASSWORD) 
VALUES (@MASV, @HO, @TEN, @NGAYSINH, @DIACHI, @MALOP, @PASSWORD)
--THÊM MÔN HỌC
ALTER PROC [dbo].[SP_ThemMonHoc]
@MAMH nchar(5),
@TENMH NVARCHAR(50)
AS
if exists(select MAMH FROM MONHOC WHERE MAMH=@MAMH) RAISERROR('DA TON TAI MA MON HOC NAY',16,1,50005)
ELSE
insert into MONHOC(MAMH, TENMH) 
VALUES (@MAMH, @TENMH)
--THÊM LỚP
ALTER PROC [dbo].[SP_ThemLop]
@MALOP nchar(8),
@TENLOP NVARCHAR(50),
@MAKH nchar(3)
AS
if exists(select MALOP FROM LOP WHERE MALOP=@MALOP) RAISERROR('DA TON TAI MA LOP NAY',16,1,50004)
ELSE
insert into LOP (MALOP, TENLOP, MAKH) 
VALUES (@MALOP, @TENLOP, @MAKH)
--THÊM KHOA
ALTER PROC [dbo].[SP_ThemKhoa]
@MAKH nchar(8),
@TENKH NVARCHAR(50),
@MACS nchar(3)
AS
if exists(select MAKH FROM KHOA WHERE MAKH=@MAKH) RAISERROR('DA TON TAI MA KHOA NAY',16,1,50003)
ELSE
insert into KHOA (MAKH, TENKH, MACS) 
VALUES (@MAKH, @TENKH, @MACS)
--
